CREATE TABLE building_permits (
    PermitNum VARCHAR(50) NOT NULL PRIMARY KEY,
    PermitClass VARCHAR(50),
    PermitClassMapped VARCHAR(50),
    PermitTypeMapped VARCHAR(50),
    PermitTypeDesc VARCHAR(255),
    Description TEXT,
    HousingUnits INTEGER,
    HousingUnitsRemoved INTEGER,
    HousingUnitsAdded INTEGER,
    EstProjectCost REAL,
    AppliedDate VARCHAR(50),
    IssuedDate VARCHAR(50),
    ExpiresDate VARCHAR(50),
    CompletedDate VARCHAR(50),
    StatusCurrent VARCHAR(50),
    RelatedMup VARCHAR(50),
    OriginalAddress1 VARCHAR(255),
    OriginalCity VARCHAR(100),
    OriginalState VARCHAR(2),
    OriginalZip INTEGER,
    ContractorCompanyName VARCHAR(255),
    Link TEXT,
    Latitude REAL,
    Longitude REAL,
    Location1 VARCHAR(255),
    NeighborDistrict VARCHAR(100)
);